export default {
  'UK_FEMALE': 'UK English Female',
  'UK_MALE': 'UK English Male',
  'US_FEMALE': 'US English Female',
  'US_MALE': 'US English Male',
  'SPANISH': 'Spanish Female',
  'FRENCH': 'French Female',
  'DEUTSCH': 'Deutsch Female',
  'ITALIAN': 'Italian Female',
  'GREEK': 'Greek Female',
  'HUNGRARIAN': 'Hungarian Female',
  'TURKISH': 'Turkish Female',
  'RUSSIAN': 'Russian Female',
  'DUTCH': 'Dutch Female',
  'SWEDISH': 'Swedish Female',
  'AUSTRALIAN': 'Australian Female',
  'ICELANDIC': 'Icelandic Male',
  'POLISH': 'Polish Female',
  'WELSH': 'Welsh Male'
  // 'Norwegian Female',
  // 'Japanese Female',
  // 'Korean Female',
  // 'Chinese Female',
  // 'Hindi Female',
  // 'Serbian Male',
  // 'Croatian Male',
  // 'Bosnian Male',
  // 'Romanian Male',
  // 'Catalan Male',
  // 'Finnish Female',
  // 'Afrikaans Male',
  // 'Albanian Male',
  // 'Arabic Male',
  // 'Armenian Male',
  // 'Czech Female',
  // 'Danish Female',
  // 'Esperanto Male',
  // 'Hatian Creole Female',
  // 'Indonesian Female',
  // 'Latin Female',
  // 'Latvian Male',
  // 'Macedonian Male',
  // 'Moldavian Male',
  // 'Montenegrin Male',
  // 'Brazilian Portuguese Female',
  // 'Portuguese Female',
  // 'Serbo-Croatian Male',
  // 'Slovak Female',
  // 'Spanish Latin American Female',
  // 'Swahili Male',
  // 'Tamil Male',
  // 'Thai Female',
  // 'VIETNAMESE':'Vietnamese Male',
}
